# Site settings
title: Blog of Dale Knauss
email: daleknauss@gmail.com
description: > # Thoughts on startups, mindfulness,
    code, people, and strange things that go bump in the night.
baseurl: "" # the subpath of your site, e.g. /blog
url: "daleknauss.com" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
single_footer: '<p>The writer community loves your content. Writer &copy; 2015 <a href="/">latest posts</a></p>'
footer_links:
    Writer: ['Dale Knauss &copy; 2015', '/about']
default_author_name: 'Dale Knauss'
default_avatar: dale
default_author_url: '/about'

# Build settings
markdown: kramdown
